version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test #change dockerfile name to 'Dockerfile.prod' for production
    container_name: zania-fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: zania
      POSTGRES_PASSWORD: zania
      POSTGRES_DB: test # change database name to 'prod' for production
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
